#!/usr/bin/env bash
# =====================================================================
# deploy_osmosis.sh — deploy the Bluechip stack to an Osmosis chain
# =====================================================================
# usage: ./deploy_osmosis.sh [env-file]
#
#   env-file   osmo_testnet.env (default) or osmosis_mainnet.env
#
# Stores the five wasms (factory, creator_pool, router, cw20_base,
# cw721_base), instantiates the factory and the router, then verifies
# the deploy by reading the factory config back and probing
# ConvertNativeToUsd so the live x/twap rate is visible.
#
# Store modes (env var STORE_MODE, default "direct"):
#   direct  -> `wasm store` each artifact. Permissionless on osmo-test-5;
#              on osmosis-1 only valid if governance granted the deployer
#              upload permission.
#   gov     -> skip uploads entirely; all five *_CODE_ID values must be
#              set in the env file (from passed StoreCode proposals).
#
# Resumable: progress is checkpointed into $STATE_FILE after every
# stage. Re-running skips anything already recorded there — delete the
# state file (or individual lines) to force a redo.
#
# Mainnet guards: on osmosis-1 the script refuses to run without an
# explicit PROTOCOL_WALLET (the fee wallet must be the multisig, not
# the deploy key) and a non-empty PRICING_POOL_ID.
#
# Prerequisites:
#   1. osmosisd and jq on PATH
#   2. A key named per ${FROM} in the local keyring with gas balance
#      >= MIN_GAS_BALANCE (testnet faucet: faucet.testnet.osmosis.zone)
#   3. Wasms present in ${ARTIFACTS}/ — build them with:
#        make optimize-all   (reproducible, deployable)
#        make build          (fast local build, testnet only)
#      cw20_base.wasm / cw721_base.wasm fall back to the copies at the
#      repo root when absent from ${ARTIFACTS}/.
#
# Testing knob: FACTORY_WASM_FILE=factory-integration.wasm deploys the
# integration_short_timing factory build (short timelocks, 30s pool-create
# rate limit) that `make optimize-factory` also produces. Testnet only —
# NEVER deploy that artifact to a public production chain.
# =====================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${1:-$REPO_ROOT/osmo_testnet.env}"
export ENV_FILE
# shellcheck disable=SC1091
source "$REPO_ROOT/scripts/_helpers.sh"

STORE_MODE="${STORE_MODE:-direct}"
FACTORY_WASM_FILE="${FACTORY_WASM_FILE:-factory.wasm}"
STATE_PATH="$REPO_ROOT/$STATE_FILE"

ensure_tools
ensure_key

# ---- Mainnet guards -------------------------------------------------
if [ "$CHAIN_ID" = "osmosis-1" ]; then
    if [ -z "${PROTOCOL_WALLET:-}" ]; then
        echo "error: refusing a mainnet deploy without an explicit PROTOCOL_WALLET" >&2
        echo "       set it in $ENV_FILE (this should be the protocol multisig)" >&2
        exit 1
    fi
    if [ -z "${PRICING_POOL_ID:-}" ]; then
        echo "error: PRICING_POOL_ID is empty — point it at the deepest OSMO/USDC pool" >&2
        exit 1
    fi
    if [ "$FACTORY_WASM_FILE" != "factory.wasm" ]; then
        echo "error: refusing to deploy '$FACTORY_WASM_FILE' to mainnet — only the" >&2
        echo "       prod factory build (factory.wasm) may ship to a public chain" >&2
        exit 1
    fi
fi
PROTOCOL_WALLET="${PROTOCOL_WALLET:-$ADDR}"

# ---- Balance check --------------------------------------------------
if ! BAL_JSON="$(query_json bank balances "$ADDR")"; then
    echo "error: cannot reach $NODE" >&2
    echo "$BAL_JSON" >&2
    exit 1
fi
GAS_BAL="$(echo "$BAL_JSON" | jq -r --arg d "$NATIVE_DENOM" \
    '.balances[]? | select(.denom == $d) | .amount' 2>/dev/null || echo 0)"
[ -z "$GAS_BAL" ] && GAS_BAL=0
if [ "$GAS_BAL" -lt "$MIN_GAS_BALANCE" ]; then
    echo "error: $ADDR has only $GAS_BAL $NATIVE_DENOM, need >= $MIN_GAS_BALANCE" >&2
    echo "       faucet: https://faucet.testnet.osmosis.zone/" >&2
    exit 1
fi

echo "deployer:      $ADDR"
echo "gas balance:   $GAS_BAL $NATIVE_DENOM (>= $MIN_GAS_BALANCE required)"
echo "chain:         $CHAIN_ID via $NODE"
echo "store mode:    $STORE_MODE"
echo "fee wallet:    $PROTOCOL_WALLET"
echo ""

# ---- Resume from a previous partial run -----------------------------
if [ -f "$STATE_PATH" ]; then
    echo "found $STATE_FILE — resuming (already-completed stages are skipped)"
    # shellcheck disable=SC1090
    source "$STATE_PATH"
    echo ""
fi

# Append a KEY="VALUE" line to the state file (idempotent per key).
checkpoint() {
    local key="$1" value="$2"
    if [ ! -f "$STATE_PATH" ]; then
        {
            echo "# Auto-generated by deploy_osmosis.sh — DO NOT EDIT MANUALLY"
            echo "# Sourced by the scripts/ test helpers alongside $(basename "$ENV_FILE")."
        } > "$STATE_PATH"
    fi
    if ! grep -q "^${key}=" "$STATE_PATH"; then
        printf '%s="%s"\n' "$key" "$value" >> "$STATE_PATH"
    fi
}

# ---- Pre-flight: pricing pool sanity (warn-only) --------------------
# The factory refuses pricing_pool_id 0 but cannot verify at instantiate
# time that the pool actually trades NATIVE_DENOM/USD_QUOTE_DENOM — a
# wrong id surfaces later as a failed ConvertNativeToUsd probe. Check
# the denoms up front where the CLI supports it.
if POOL_JSON="$(query_json poolmanager pool "$PRICING_POOL_ID" 2>/dev/null)"; then
    if ! echo "$POOL_JSON" | grep -q "$USD_QUOTE_DENOM" \
        || ! echo "$POOL_JSON" | grep -q "$NATIVE_DENOM"; then
        echo "WARNING: pool $PRICING_POOL_ID does not appear to trade" >&2
        echo "         $NATIVE_DENOM / $USD_QUOTE_DENOM. The post-deploy" >&2
        echo "         pricing probe will likely fail; commits fail closed" >&2
        echo "         until the pricing route is fixed." >&2
        echo "" >&2
    fi
fi

# ---- 1. Upload wasms ------------------------------------------------
echo "[1/3] wasm code IDs"

upload_wasm() {
    local file="$1" label="$2"
    local path="$ARTIFACTS/$file"
    # cw20_base / cw721_base ship at the repo root (pinned upstream
    # releases); fall back there when not staged into artifacts/.
    if [ ! -f "$path" ] && [ -f "$REPO_ROOT/$file" ]; then
        path="$REPO_ROOT/$file"
    fi
    if [ ! -f "$path" ]; then
        echo "error: missing $ARTIFACTS/$file — run \`make optimize-all\` (or \`make build\`) first" >&2
        return 1
    fi
    local result code_id
    result="$(submit_tx wasm store "$path")"
    code_id="$(extract_attr "$result" store_code code_id)"
    if [ -z "$code_id" ] || [ "$code_id" = "null" ]; then
        echo "error: could not extract code_id for $file" >&2
        return 1
    fi
    printf "      %-16s code_id=%s  (%s)\n" "$label" "$code_id" "$path" >&2
    echo "$code_id"
}

# Each code ID resolves in priority order:
#   state file (resume) > env file (gov mode / manual pin) > fresh upload
resolve_code_id() {
    local var="$1" file="$2" label="$3"
    local current="${!var:-}"
    if [ -n "$current" ]; then
        printf "      %-16s code_id=%s  (reused)\n" "$label" "$current" >&2
        echo "$current"
        return 0
    fi
    if [ "$STORE_MODE" = "gov" ]; then
        echo "error: STORE_MODE=gov but $var is empty in $ENV_FILE" >&2
        echo "       fill in the code IDs from the passed StoreCode proposals" >&2
        return 1
    fi
    upload_wasm "$file" "$label"
}

CW20_CODE_ID="$(resolve_code_id CW20_CODE_ID cw20_base.wasm 'CW20 base')"
checkpoint CW20_CODE_ID "$CW20_CODE_ID"
CW721_CODE_ID="$(resolve_code_id CW721_CODE_ID cw721_base.wasm 'CW721 base')"
checkpoint CW721_CODE_ID "$CW721_CODE_ID"
CREATOR_POOL_CODE_ID="$(resolve_code_id CREATOR_POOL_CODE_ID creator_pool.wasm 'Creator pool')"
checkpoint CREATOR_POOL_CODE_ID "$CREATOR_POOL_CODE_ID"
FACTORY_CODE_ID="$(resolve_code_id FACTORY_CODE_ID "$FACTORY_WASM_FILE" 'Factory')"
checkpoint FACTORY_CODE_ID "$FACTORY_CODE_ID"
ROUTER_CODE_ID="$(resolve_code_id ROUTER_CODE_ID router.wasm 'Router')"
checkpoint ROUTER_CODE_ID "$ROUTER_CODE_ID"
checkpoint ADMIN_ADDR "$ADDR"

# ---- 2. Instantiate factory -----------------------------------------
echo ""
echo "[2/3] instantiate factory"

if [ -n "${FACTORY_ADDR:-}" ]; then
    echo "      factory already at $FACTORY_ADDR (from $STATE_FILE), skipping"
else
    # This JSON shape is pinned by the factory regression test
    # `deploy_script_instantiate_json_deserializes` — change them together.
    # threshold_payout_amounts is deliberately omitted: the serde default
    # is the canonical launch split and the same test asserts it validates.
    #
    # gamm_pool_creation_fee is the fee x/gamm auto-charges at threshold
    # crossing (MsgCreateBalancerPool). The pool funds it from the 1%
    # commit-fee retention (protocol revenue, never the creator) and
    # self-corrects against the LIVE poolmanager fee at crossing. Set it
    # to the chain's real fee COIN — `osmosisd q poolmanager params`:
    #   osmo-test-5: 1000000 uosmo (native-denominated, paid directly)
    #   osmosis-1:   20000000 Noble-USDC ibc/… (the pool swaps its native
    #                retention into the fee coin via the pricing pool)
    # The denom must be NATIVE_DENOM or USD_QUOTE_DENOM (validated at
    # instantiate; anything else is unroutable at crossing).
    GAMM_POOL_CREATION_FEE="${GAMM_POOL_CREATION_FEE:-0}"
    GAMM_POOL_CREATION_FEE_DENOM="${GAMM_POOL_CREATION_FEE_DENOM:-$NATIVE_DENOM}"
    FACTORY_INIT="$(jq -nc \
        --arg admin            "$ADDR" \
        --arg wallet           "$PROTOCOL_WALLET" \
        --arg native_denom     "$NATIVE_DENOM" \
        --arg usd_quote        "$USD_QUOTE_DENOM" \
        --arg pricing_pool     "$PRICING_POOL_ID" \
        --arg twap_window      "$TWAP_WINDOW_SECONDS" \
        --arg threshold_usd    "$COMMIT_THRESHOLD_LIMIT_USD" \
        --arg fee_bc           "$COMMIT_FEE_BLUECHIP" \
        --arg fee_cr           "$COMMIT_FEE_CREATOR" \
        --arg max_lock         "$MAX_BLUECHIP_LOCK_PER_POOL" \
        --arg lock_days        "$CREATOR_EXCESS_LIQUIDITY_LOCK_DAYS" \
        --arg creation_fee     "$POOL_CREATION_FEE" \
        --arg gamm_fee         "$GAMM_POOL_CREATION_FEE" \
        --arg gamm_fee_denom   "$GAMM_POOL_CREATION_FEE_DENOM" \
        --arg emergency_delay  "$EMERGENCY_WITHDRAW_DELAY_SECONDS" \
        --arg cw20_id          "$CW20_CODE_ID" \
        --arg cw721_id         "$CW721_CODE_ID" \
        --arg pool_id          "$CREATOR_POOL_CODE_ID" \
        '{
            factory_admin_address:              $admin,
            bluechip_wallet_address:            $wallet,
            bluechip_denom:                     $native_denom,
            usd_quote_denom:                    $usd_quote,
            pricing_pool_id:                    ($pricing_pool    | tonumber),
            twap_window_seconds:                ($twap_window     | tonumber),
            commit_threshold_limit_usd:         $threshold_usd,
            commit_fee_bluechip:                $fee_bc,
            commit_fee_creator:                 $fee_cr,
            max_bluechip_lock_per_pool:         $max_lock,
            creator_excess_liquidity_lock_days: ($lock_days       | tonumber),
            pool_creation_fee:                  $creation_fee,
            gamm_pool_creation_fee:             {denom: $gamm_fee_denom, amount: $gamm_fee},
            emergency_withdraw_delay_seconds:   ($emergency_delay | tonumber),
            cw20_token_contract_id:             ($cw20_id         | tonumber),
            cw721_nft_contract_id:              ($cw721_id        | tonumber),
            create_pool_wasm_contract_id:       ($pool_id         | tonumber)
        }')"

    # --admin: keep a migration authority so audited wasm fixes can ship.
    # Post-deploy checklist: rotate it to the protocol multisig.
    FACTORY_RESULT="$(submit_tx wasm instantiate "$FACTORY_CODE_ID" "$FACTORY_INIT" \
        --label "bluechip_factory" --admin "$ADDR")"
    FACTORY_ADDR="$(extract_attr "$FACTORY_RESULT" instantiate _contract_address)"
    if [ -z "$FACTORY_ADDR" ]; then
        echo "error: could not extract factory address from instantiate tx" >&2
        exit 1
    fi
    echo "      factory: $FACTORY_ADDR"
fi
checkpoint FACTORY_ADDR "$FACTORY_ADDR"

# ---- 3. Instantiate router -------------------------------------------
echo ""
echo "[3/3] instantiate router"

if [ -n "${ROUTER_ADDR:-}" ]; then
    echo "      router already at $ROUTER_ADDR (from $STATE_FILE), skipping"
else
    ROUTER_INIT="$(jq -nc \
        --arg factory "$FACTORY_ADDR" \
        --arg denom   "$NATIVE_DENOM" \
        --arg admin   "$ADDR" \
        '{factory_addr: $factory, bluechip_denom: $denom, admin: $admin}')"

    ROUTER_RESULT="$(submit_tx wasm instantiate "$ROUTER_CODE_ID" "$ROUTER_INIT" \
        --label "bluechip_router" --admin "$ADDR")"
    ROUTER_ADDR="$(extract_attr "$ROUTER_RESULT" instantiate _contract_address)"
    if [ -z "$ROUTER_ADDR" ]; then
        echo "error: could not extract router address from instantiate tx" >&2
        exit 1
    fi
    echo "      router:  $ROUTER_ADDR"
fi
checkpoint ROUTER_ADDR "$ROUTER_ADDR"

# ---- Verification -----------------------------------------------------
echo ""
echo "=================================================="
echo "verification"
echo "=================================================="

echo "--- factory config readback ---"
if CONFIG="$(query_smart "$FACTORY_ADDR" '{"factory":{}}')"; then
    echo "$CONFIG" | jq '{
        bluechip_denom:             .factory.bluechip_denom,
        pricing_pool_id:            .factory.pricing_pool_id,
        usd_quote_denom:            .factory.usd_quote_denom,
        twap_window_seconds:        .factory.twap_window_seconds,
        commit_threshold_limit_usd: .factory.commit_threshold_limit_usd,
        pool_creation_fee:          .factory.pool_creation_fee,
        bluechip_wallet_address:    .factory.bluechip_wallet_address
    }' 2>/dev/null || echo "$CONFIG"
else
    echo "WARNING: factory config query failed" >&2
fi

echo ""
echo "--- live x/twap pricing probe: ConvertNativeToUsd(1 ${NATIVE_DENOM%u*}OSMO) ---"
PROBE_MSG='{"pool_factory_query":{"convert_native_to_usd":{"amount":"1000000"}}}'
if PROBE="$(query_smart "$FACTORY_ADDR" "$PROBE_MSG")" \
    && USD="$(echo "$PROBE" | jq -re '.amount' 2>/dev/null)"; then
    USD_HUMAN="$(awk -v u="$USD" 'BEGIN { printf "%.4f", u/1000000 }')"
    echo "1 OSMO ≈ \$$USD_HUMAN USD (rate_used=$(echo "$PROBE" | jq -r '.rate_used'))"
    echo "pricing route OK — commits will value correctly"
else
    echo "WARNING: pricing probe FAILED. Commits fail closed until this works." >&2
    echo "         Likely causes: PRICING_POOL_ID ($PRICING_POOL_ID) is not a" >&2
    echo "         $NATIVE_DENOM/$USD_QUOTE_DENOM pool, or it lacks" >&2
    echo "         ${TWAP_WINDOW_SECONDS}s of TWAP history. Fix via the 48h" >&2
    echo "         ProposeConfigUpdate flow or redeploy with a corrected env." >&2
    echo "         raw: ${PROBE:-<no response>}" >&2
fi

echo ""
echo "--- router config readback ---"
if RCONFIG="$(query_smart "$ROUTER_ADDR" '{"config":{}}')"; then
    echo "$RCONFIG" | jq . 2>/dev/null || echo "$RCONFIG"
else
    echo "WARNING: router config query failed" >&2
fi

echo ""
echo "=================================================="
echo "deploy complete"
echo "=================================================="
echo "factory:  $FACTORY_ADDR"
echo "router:   $ROUTER_ADDR"
echo "state:    $STATE_PATH"
echo ""
echo "NEXT:"
echo "  scripts/status.sh                        # health overview"
echo "  scripts/create_commit_pool.sh 'My Token' MYTOK"
echo "  scripts/cross_threshold.sh <pool_addr>   # commit past the USD threshold"
echo "  scripts/run_lifecycle_test.sh            # full automated lifecycle"
